### ISSUE TITLE
0.0.3 not available from Maven

### ISSUE THREAD

**Issue by oseparovic** [kobakei/Android-RateThisApp#25]
Maybe it's too early but it doesn't look like the latest release has made it to the Maven central repo yet.

http://javalibs.com/artifact/com.kobakei/ratethisapp

**Comment by kobakei** [comment]
Sorry, I'm busy and have not released 0.0.3 yet
If you don't need Thai language, you can use 0.0.2

**Comment by oseparovic** [comment]
No problem it's what I was using now, just bringing it up because it's listed in the readme documentation as the current version. Thanks for the great work :+1:

**Comment by kobakei** [comment]
0.0.3 has been released.
