### ISSUE TITLE
Missing Title and Message on Android Marshmallow

### ISSUE THREAD

**Issue by damai007** [kobakei/Android-RateThisApp#31]
Hi, first of all, thank you so much for creating this library. As I tried on Android Marshmallow, the title and message are missing. I see in **RateThisApp.java:showRateDialog()**, it still uses AlertDialog which uses a different constructor with theme for Android Lollilop and Marshmallow. As the result, I change the code (as described on [here](http://stackoverflow.com/a/33257083/4569155)) and it works like a charm.
So, I hope it will be fixed on the next release.

*Sorry for my English. :dancers:

**Comment by kobakei** [comment]
I cannot reproduce the issue on my Nexus5 Android Marshmallow.
Would you provide more info (code, styles etc) ?

**Comment by damai007** [comment]
I'm still having this problem on my Genymotion emulator with Marshmallow installed on it. You can see the screenshot I uploaded here:
> https://cloud.githubusercontent.com/assets/5790484/13642175/fd7e93ac-e64d-11e5-8bf8-b0375dbfd7ef.png

I change the code (as describe [here](http://stackoverflow.com/a/33257083/4569155)), and it should be like this:
> https://cloud.githubusercontent.com/assets/5790484/13642466/3775aeaa-e64f-11e5-9f29-4a169b3cbfe6.png

FYI, I compiled my project with SDK version 22, so I think maybe you tried on version 23 instead.

**Comment by kobakei** [comment]
@damai007 
Today I have released 1.0.1.
The new version uses `android.support.v7.app.AlertDialog` instead of `android.app.AlertDialog`. And the version also have showRateDialog method with theme ID argument.
I think that the new one will make easy to set style as material design for developers.
Please take a look sample app.
