### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by mlayton20** [kobakei/Android-RateThisApp#49]
I was having the following error when I tried using the code in an Activity:

You need to use a Theme.AppCompat theme (or descendant) with this activity

This is because in my AndroidManifest.xml I'm using the following theme:
android:theme="@android:style/Theme.NoTitleBar"

Changing the above to the below for the Activity that shows the RateApp dialog fixed this for me.
android:theme="@style/Theme.AppCompat.NoActionBar"

I got this solution from the below article:
http://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity

**Comment by jewom** [comment]
For me, using RateThisApp.showRateDialog(this) instead of RateThisApp.showRateDialog(applicationContext) work
