### ISSUE TITLE
Readme suggests onStart be called in Activity onStart which may be misleading

### ISSUE THREAD

**Issue by oseparovic** [kobakei/Android-RateThisApp#71]
From what I can tell the `onStart` life-cycle method is fired every time an `AppCompatActivity` becomes visible again. Doesn't this mean calling `RateThisApp.onStart(this);` in `protected void onStart()` could result in the startup counter incrementing multiple times in one user session? In my applications the MainActivity represents a home page and a user can easily navigate away and come back again 10-20 times in a single session.

If my understanding above is correct I would recommend you suggest `RateThisApp.onStart(this);` be called in the launcher Activity's `onCreate` method instead as this should persist for the duration of the user's session.

**Comment by kobakei** [comment]
Thanks. I have fixed README.
